name: Docker - Build Image Workflow
on: 
    workflow_call: 
        inputs:
            Container_Registry:
                required: true
                type: string
            Container_Registry_Username:
                required: true
                type: string
            Container_Build_Target:
                required: true
                type: string
            Image_Name:
                required: true
                type: string
            Build_Args:
                type: string
                default: args=none
            GitVersion_FullSemVer:
                required: false
                type: string
            GitVersion_ShortSHA:
                required: false
                type: string
            GitVersion_MajorMinorPatch:
                required: false
                type: string
            Image_Description:
                required: true
                type: string

        secrets:
            repo_pat:
                required: true
        

jobs:          
    build_image:
        name: Build ${{ inputs.Container_Build_Target }}
        runs-on: ubuntu-latest
        # needs: gitversion
        permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    
        steps:
          - name: Printout Inputs
            run: |
              echo "Docker Registry: ${{ inputs.Container_Registry}}"
              echo "Docker Username: ${{ inputs.Container_Registry_Username}}"
              echo "Docker Target: ${{ inputs.Container_Build_Target}}"
              echo "Image Name: ${{inputs.Image_Name}}"
              echo "GitVersion SemVer: ${{inputs.GitVersion_FullSemVer}}"

          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
    
          # Login against a Docker registry except on PR
          # https://github.com/docker/login-action
          - name: Log into registry ${{  inputs.Container_Registry }}
            if: github.event_name != 'pull_request'
            uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
            with:
              registry: ${{  inputs.Container_Registry }}
              username: ${{  inputs.Container_Registry_Username }}
              password: ${{ secrets.repo_pat }}

          #     Extract metadata (tags, labels) for Docker
          # https://github.com/docker/metadata-action
          - name: Extract Docker metadata
            id: meta
            uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
            with:
              images: ${{ inputs.Container_Registry }}/${{ inputs.Image_Name }}
              tags: |
                type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Australia/Perth'}}
                type=raw,value=latest,enable={{is_default_branch}}
                type=semver,pattern={{version}},value=${{inputs.GitVersion_MajorMinorPatch}}-${{inputs.GitVersion_ShortSHA}}
              labels: |
                org.opencontainers.image.description=${{ inputs.Image_Description }}
                org.opencontainers.image.version=${{ inputs.GitVersion_FullSemVer }}
          # Build and push Docker image with Buildx (don't push on PR)
          # https://github.com/docker/build-push-action
          - name: Build and push Docker image
            id: build-and-push
            uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
            with:
              context: .
              # platforms: linux/amd64,linux/arm64
              push: ${{ github.event_name != 'pull_request' }}
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}
              cache-from: type=gha
              cache-to: type=gha,mode=max
              target: ${{  inputs.Container_Build_Target }}
              build-args: |
                "CONTAINER_REGISTRY=${{  inputs.Container_Registry }}"
                "BASEIMAGE_VERSION=${{ inputs.GitVersion_MajorMinorPatch }}-${{inputs.GitVersion_ShortSHA}}"
                "${{ inputs.Build_Args }}"
    
          - name: Build Image Summary
            run: |
              echo "### Image Summary - ${{ inputs.Container_Build_Target}}" >> $GITHUB_STEP_SUMMARY
              echo "" >> $GITHUB_STEP_SUMMARY
              # Set Table Row Header
              echo "| Name | Value |" >> $GITHUB_STEP_SUMMARY
              echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
              echo "| Container Registry | ${{ inputs.Container_Registry }}|" >> $GITHUB_STEP_SUMMARY
              echo "| Image Name | ${{ inputs.Image_Name}}|"  >> $GITHUB_STEP_SUMMARY
              echo "| Image Tag | ${{inputs.GitVersion_MajorMinorPatch}}-${{inputs.GitVersion_ShortSHA}}|"  >> $GITHUB_STEP_SUMMARY
              echo "| Image Build Target |${{ inputs.Container_Build_Target}}|"  >> $GITHUB_STEP_SUMMARY
              
              
              echo " #### Image Tags" >> $GITHUB_STEP_SUMMARY
              echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
              
              echo " #### Image Labels" >> $GITHUB_STEP_SUMMARY
              echo "${{ steps.meta.outputs.labels }}" >> $GITHUB_STEP_SUMMARY
              
              echo " #### Pull Image " >> $GITHUB_STEP_SUMMARY
              echo "```" >>> $GITHUB_STEP_SUMMARY
              echo "docker pull ${{ inputs.Container_Registry }}/${{ inputs.Image_Name}}:${{inputs.GitVersion_MajorMinorPatch}}-${{inputs.GitVersion_ShortSHA}}" >> $GITHUB_STEP_SUMMARY
              echo "```" >>> $GITHUB_STEP_SUMMARY
