name: Check AWS Release Version

on:
  schedule:
  - cron: '32 22 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ "feature/amazon-linux-version-check" ]


jobs:
  check_version:
    name: Check AL Version
    runs-on: ubuntu-latest
    steps:
      - name: Pull Image
        run: |
          docker pull amazonlinux:2023 
      - name: Get Release Name
        id: system_release
        run: |
          echo "AL2023_SYSTEM_RELEASE=$(docker run amazonlinux:2023 cat /etc/system-release | sed -r 's%[A-Za-z() ]%%g')" >> $GITHUB_OUTPUT
      - name: Print Output | AL2023_SYSTEM_RELEASE
        run: |
          echo "AL2023 System Release Value: ${{ steps.system_release.outputs.AL2023_SYSTEM_RELEASE }}"    
      - name: Summary Output | AL2023_SYSTEM_RELEASE
        run: |
          echo "### AL2023 Release Summary" >> $GITHUB_STEP_SUMMARY
          echo "AL2023 System Release Value: ${{ steps.system_release.outputs.AL2023_SYSTEM_RELEASE }}" >> $GITHUB_STEP_SUMMARY

# 2023.6.20250115  
#RELEASE_VER=$(echo "$(cat /etc/system-release)" | sed -r 's%[A-Za-z() ]%%g')


