name: Docker - Build Images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 22 * * *'
  push:
    branches: [ "main", "feature/workflows-base", "bugfix/*" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitversion:  
    uses: thegippygeek/gha_poc/.github/workflows/gitversion.yml@v1.0.0

  build-base:
    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@v1.0.0
    needs: gitversion
    permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    with:
        Docker_Registry: ${{ vars.DOCKER_REGISTRY }}
        Docker_Username: ${{ vars.DOCKER_USERNAME }}
        Docker_Target: al2023-base
        Image_Name: ${{ github.repository }}
        GitVersion_FullSemVer: ${{ needs.gitversion.outputs.GitVersion_FullSemVer }}
        GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
    secrets:
        repo_pat: ${{ secrets.DOCKERHUB }}

  build-dotnet-8-sdks-runtimes:
    needs: [gitversion, build-base]
    strategy:
        matrix:
            target: [al2023-dotnet-sdk, al2023-dotnet-runtime]
                
    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@v1.0.0
    permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    with:
        Docker_Registry: ${{ vars.DOCKER_REGISTRY }}
        Docker_Username: ${{ vars.DOCKER_USERNAME }}
        Docker_Target: ${{ matrix.target }}
        Image_Name: ${{ github.repository }}-${{ matrix.target}}-8
        GitVersion_FullSemVer: ${{needs.gitversion.outputs.GitVersion_FullSemVer}}
        GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
        Build_Args: DOTNET_VERSION=8.0
    secrets:
        repo_pat: ${{ secrets.DOCKERHUB }}

  build-dotnet-6-sdks-runtimes:
    needs: [gitversion, build-base]
    strategy:
        matrix:
            target: [al2023-dotnet-sdk, al2023-dotnet-runtime]  
                      
    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@v1.0.0
    permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    with:
        Docker_Registry: ${{ vars.DOCKER_REGISTRY }}
        Docker_Username: ${{ vars.DOCKER_USERNAME }}
        Docker_Target: ${{ matrix.target }}
        Image_Name: ${{ github.repository }}-${{ matrix.target}}-6
        GitVersion_FullSemVer: ${{needs.gitversion.outputs.GitVersion_FullSemVer}}
        GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
        Build_Args: DOTNET_VERSION=6.0
    secrets:
        repo_pat: ${{ secrets.DOCKERHUB }}
      