name: Docker - Build Images

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '32 22 * * *'
  push:
    branches: [ "feature/*", "hotfix/*",  ]
    # # Publish semver tags as releases.
    # tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

    
jobs:
  gitversion: 
    name: GitVersion 
    uses: thegippygeek/gha_poc/.github/workflows/gitversion.yml@hotfix/update-inputs-to-container

  build-base:
    name: Amazon Linux 2023
    needs: gitversion
    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@hotfix/update-inputs-to-container
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    with:
      Container_Registry: ${{ vars.CONTAINER_REGISTRY }}
      Container_Registry_Username: ${{ github.actor }}
      # Container_Registry_Username: ${{ vars.DOCKER_USERNAME }}
      Container_Build_Target: al2023-base
      Image_Name: ${{ github.repository }}
      Image_Description: "Amazon Linux 2023 Base Image to build sdks/runtimes upon"
      GitVersion_FullSemVer: ${{ needs.gitversion.outputs.GitVersion_FullSemVer }}
      GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
      GitVersion_MajorMinorPatch: ${{ needs.gitversion.outputs.GitVersion_MajorMinorPatch }}
    secrets:
      repo_pat: ${{ secrets.GITHUB_TOKEN }}
        # repo_pat: ${{ secrets.DOCKERHUB }}

  build-dotnet-8-sdks-runtimes:
    name: AL2023 Dotnet 8                  
    needs: [gitversion, build-base]
    strategy:
        matrix:
            target: [al2023-dotnet-sdk, al2023-dotnet-runtime]
                
    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@hotfix/update-inputs-to-container
    permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    with:
        Container_Registry: ${{ vars.CONTAINER_REGISTRY }}
        Container_Registry_Username: ${{ github.actor }}
        # Container_Registry_Username: ${{ vars.DOCKER_USERNAME }}
        Container_Build_Target: ${{ matrix.target }}
        Image_Name: ${{ github.repository }}-${{ matrix.target}}-8
        Image_Description: "Amazon Linux 2023 with Dotnet 8"
        GitVersion_FullSemVer: ${{needs.gitversion.outputs.GitVersion_FullSemVer}}
        GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
        GitVersion_MajorMinorPatch: ${{ needs.gitversion.outputs.GitVersion_MajorMinorPatch }}
        Build_Args: DOTNET_VERSION=8.0
    secrets:
        # repo_pat: ${{ secrets.DOCKERHUB }}
        repo_pat: ${{ secrets.GITHUB_TOKEN }}

##### DOTNET6 #####
  build-dotnet-6-sdks-runtimes:
    name: AL2023 Dotnet 6                  
    needs: [gitversion, build-base]
    strategy:
        matrix:
            target: [al2023-dotnet-sdk, al2023-dotnet-runtime]  
    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@hotfix/update-inputs-to-container
    permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    with:
        Container_Registry: ${{ vars.CONTAINER_REGISTRY }}
        Container_Registry_Username: ${{ github.actor }}
        # Container_Registry_Username: ${{ vars.DOCKER_USERNAME }}
        Container_Build_Target: ${{ matrix.target }}
        Image_Name: ${{ github.repository }}-${{ matrix.target}}-6
        Image_Description: "Amazon Linux 2023 with Dotnet 6"
        GitVersion_FullSemVer: ${{needs.gitversion.outputs.GitVersion_FullSemVer}}
        GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
        GitVersion_MajorMinorPatch: ${{ needs.gitversion.outputs.GitVersion_MajorMinorPatch }}
        Build_Args: DOTNET_VERSION=6.0
    secrets:
        # repo_pat: ${{ secrets.DOCKERHUB }}
        repo_pat: ${{ secrets.GITHUB_TOKEN }}

  build-nodejs:
    name: AL2023 NodeJS
    needs: [gitversion, build-base]
    strategy:
        matrix:
            target: [al2023-nodejs]  

    uses: thegippygeek/gha_poc/.github/workflows/build_image.yml@hotfix/update-inputs-to-container
    permissions:
          contents: read
          packages: write
          # This is used to complete the identity challenge
          # with sigstore/fulcio when running outside of PRs.
          id-token: write
    with:
        Container_Registry: ${{ vars.CONTAINER_REGISTRY }}
        Container_Registry_Username: ${{ github.actor }}
        # Container_Registry_Username: ${{ vars.DOCKER_USERNAME }}
        Container_Build_Target: ${{ matrix.target }}
        Image_Name: ${{ github.repository }}-${{ matrix.target}}
        Image_Description: "Amazon Linux 2023 with NodeJS"
        GitVersion_FullSemVer: ${{needs.gitversion.outputs.GitVersion_FullSemVer}}
        GitVersion_ShortSHA: ${{ needs.gitversion.outputs.GitVersion_ShortSHA }}
        GitVersion_MajorMinorPatch: ${{ needs.gitversion.outputs.GitVersion_MajorMinorPatch }}
        Build_Args: NODE_VERSION=NOTSET 
    secrets:
        # repo_pat: ${{ secrets.DOCKERHUB }}
        repo_pat: ${{ secrets.GITHUB_TOKEN }}
